INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El Señor de los Anillos', 'J.R.R. Tolkien', 'Fantasia', 10);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Harry Potter y la Piedra Filosofal', 'J.K. Rowling', 'Fantasía', 15);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El Código Da Vinci', 'Dan Brown', 'Suspense', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La Caída de los Gigantes', 'Ken Follett', 'Histórico', 25);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La Chica del Tren', 'Paula Hawkins', 'Suspense', 30);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El Hobbit', 'J.R.R. Tolkien', 'Fantasia', 5);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 'Novela', 10);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La Odisea', 'Homero', 'Epopeya', 15);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La Ilíada', 'Homero', 'Epopeya', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Hamlet', 'William Shakespeare', 'Drama', 25);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Romeo y Julieta', 'William Shakespeare', 'Drama', 30);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El principito', 'Antoine de Saint-Exupéry', 'Fábula', 5);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La metamorfosis', 'Franz Kafka', 'Fantasía', 10);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 'Novela', 15);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La invención de Morel', 'Adolfo Bioy Casares', 'Novela', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Ficciones', 'Jorge Luis Borges', 'Cuentos', 25);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Rayuela', 'Julio Cortázar', 'Novela', 30);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El guardián entre el centeno', 'J.D. Salinger', 'Novela', 5);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La naranja mecánica', 'Anthony Burgess', 'Novela', 10);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La casa de los espíritus', 'Isabel Allende', 'Novela', 15);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Novela', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El túnel', 'Ernesto Sabato', 'Novela', 25);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La ciudad y los perros', 'Mario Vargas Llosa', 'Novela', 30);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Los miserables', 'Victor Hugo', 'Novela', 5);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Notre-Dame de Paris', 'Victor Hugo', 'Novela', 10);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El perfume', 'Patrick Süskind', 'Novela', 15);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('La historia interminable', 'Michael Ende', 'Fantasia', 20);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('El señor de los anillos', 'J.R.R. Tolkien', 'Fantasia', 25);
INSERT INTO libros (titulo, autor, genero, numero_ejemplares) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 'Fantasia', 30);
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Mariana', 'mariana.ortega@example.com', '2013-08-24');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Juan', 'juan.perez@example.com', '2014-03-25');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('María', 'maria.garcia@example.com', '2015-04-26');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Pedro', 'pedro.diaz@example.com', '2016-05-27');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Susana', 'susana.romero@example.com', '2017-06-28');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('José', 'jose.lopez@example.com', '2018-07-29');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Andrés', 'andres.gonzalez@example.com', '2019-08-30');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Laura', 'laura.sanchez@example.com', '2020-09-30');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('David', 'david.martinez@example.com', '2021-10-31');
INSERT INTO usuarios (nombre, email, fecha_alta) VALUES ('Isabel', 'isabel.castro@example.com', '2022-11-30');
